### ISSUE TITLE
Erro no infoga

### ISSUE THREAD

**Issue by mf256010** [Kiny-Kiny/Kiny-Painel#6]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Kiny-Painel/main.py", line 307, in <module>
    tools.consultatel()
  File "/data/data/com.termux/files/home/Kiny-Painel/tools.py", line 792, in consultatel
    phoneinfoga()
  File "/data/data/com.termux/files/home/Kiny-Painel/tools.py", line 1305, in phoneinfoga
    scanNumber(number)
  File "/data/data/com.termux/files/home/Kiny-Painel/tools.py", line 1265, in scanNumber
    if not number:
NameError: name 'number' is not defined

**Comment by Kiny-Kiny** [comment]
Use o formato +55 81 9××××-××××?
